fos_user:
  db_driver: orm
  user_class: App\Entity\User
  firewall_name: main
  # defaults
  model_manager_name: null
  use_authentication_listener: true
  use_listener: true
  use_flash_notifications: true
  use_username_form_type: true
  from_email:
    address: "symfony@localhost"
    sender_name: "Symfony Mailer"